### ISSUE TITLE
Test Suite - build location

### ISSUE THREAD

**Issue by kiritigowda** [ROCm/rpp#256]
@r-abishek - currently the test suite build binary file in source directory. We have to use the build directory for all test generated files.

**Comment by kiritigowda** [comment]
@r-abishek can you see if you can update the results to save in build location instead of source - QA_RESULTS_HOST_2023-10-30_15-51-02

**Comment by kiritigowda** [comment]
@r-abishek need this feature to get rpp-test package, can you take a look at this?

**Comment by r-abishek** [comment]
@kiritigowda Changed output writes to CWD. PR #276 fixes it.

**Comment by kiritigowda** [comment]
Issue resolved with #276 - but keeping this to change get_current_dir_name to use std::filesystem::current_path

```
#include <filesystem>
#define get_current_dir_name std::filesystem::current_path
```

**Comment by kiritigowda** [comment]
@r-abishek - the test script still creates a build folder inside tests. The build also needs to move to current path.

**Comment by kiritigowda** [comment]
TOT test suite integrated to rpp-test package
