### ISSUE TITLE
[Issue]: Location of half.hpp

### ISSUE THREAD

**Issue by trixirt** [ROCm/rpp#292]
### Problem Description

Same issue as [ MIOpen ](https://github.com/ROCm/MIOpen/issues/2672)

I am packaging rpp for Fedora, the addition of the half/ makes it impossible to set the location of half.hpp in configury.

### Operating System

Fedora Rawhide

### CPU

x86_64

### GPU

AMD Instinct MI210

### ROCm Version

ROCm 6.0.0

### ROCm Component

rpp

**Comment by kiritigowda** [comment]
@trixirt we have [FindHalf](https://github.com/ROCm/rpp/blob/master/cmake/FindHALF.cmake) to locate half headers. If you add additional location here - https://github.com/ROCm/rpp/blob/2d7adde4c09d7a9b334b6858758531ad7fa8091e/cmake/FindHALF.cmake#L35 should find the library on your setup.

**Comment by AngryLoki** [comment]
@trixirt , I think distro maintainers should install `half.hpp` into `/usr/include/half/`. I encountered this issue in Gentoo, and I will update ebuilds there in that way.

Reasoning: https://github.com/ROCm/half is a project under ROCm umbrella. MIOpen, MIVisionX, AMDMIGraphX, rpp, MIFin, rocAL and maybe other ROCm projects just decided to include it as `<half/half.hpp>`. I see this header in other projects, but again, mostly as `<half/half.hpp>`.

**Comment by kiritigowda** [comment]
@trixirt --- With the cmake you can also use the `-D HALF_DIR`or ENV Variable `HALF_DIR` to set path to include. If you still face this issue reopen.

```
-D HALF_DIR /PATH/TO/half/half.hpp
```

https://github.com/ROCm/rpp/blob/b6f334a5f779ea5327cbe398794aece30305dc37/cmake/FindHALF.cmake#L31

https://github.com/ROCm/rpp/blob/b6f334a5f779ea5327cbe398794aece30305dc37/cmake/FindHALF.cmake#L28
