### ISSUE TITLE
[Issue]: ROCm Install - Use case `Graphics` -- Required/Optional

### ISSUE THREAD

**Issue by kiritigowda** [ROCm/rpp#344]
### Problem Description

Does RPP require the graphics use case or just the rocm use case?

If this does require graphics use case what are the functionality support or rocm graphic libs required?

### Operating System

ALL

### CPU

ALL

### GPU

Other

### Other

ALL

### ROCm Version

ROCm 6.0.0

### ROCm Component

rpp

**Comment by rrawther** [comment]
graphics use case is not required for RPP. Just "rocm" use case is enough

**Comment by kiritigowda** [comment]
TODO - Remove graphics from install instructions
