### ISSUE TITLE
[Issue]: Test Prerequisites - Points to Rajy's JPEG Turbo Branch

### ISSUE THREAD

**Issue by kiritigowda** [ROCm/rpp#416]
### Problem Description

https://github.com/ROCm/rpp/blob/develop/utilities/test_suite/README.md -- 

```
sudo apt-get install nasm
sudo apt-get install wget
git clone -b 2.0.6.1 https://github.com/rrawther/libjpeg-turbo.git
cd libjpeg-turbo
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr \
      -DCMAKE_BUILD_TYPE=RELEASE  \
      -DENABLE_STATIC=FALSE       \
      -DCMAKE_INSTALL_DOCDIR=/usr/share/doc/libjpeg-turbo-2.0.3 \
      -DCMAKE_INSTALL_DEFAULT_LIBDIR=lib  \
      ..
make -j$nproc
sudo make install
```

## Solution 

Use same JPEG Turbo version as in rocAL

### Operating System

ALL

### CPU

ALL

### GPU

AMD Instinct MI300

### ROCm Version

ROCm 6.0.0

### ROCm Component

rpp

**Comment by kiritigowda** [comment]
@r-abishek -- needs upgrade to the documentation

**Comment by r-abishek** [comment]
@kiritigowda PR #419 should address this
