### ISSUE TITLE
RPP takes a long time to build from source

### ISSUE THREAD

**Issue by rrawther** [ROCm/rpp#441]
Feels like it is stuck at 99%. Need to resolve this

**Comment by rrawther** [comment]
@r-abishek : We need to look into this. I think this is happening because of the use of .hpp files. We need to use standard .h and .cpp files which will get rid of long compile times

**Comment by kiritigowda** [comment]
Use -D GPU_TARGETS="TARGET GPU GFX ID" to build custom solution to save on build time. With 6.5 we will update to use host machine GFX ID only for default build

Sample -- `cmake -D GPU_TARGETS="GFX908" ../rpp`
