### ISSUE TITLE
[Issue]: Use amdclang++ instead of clang++

### ISSUE THREAD

**Issue by LakshmiKumar23** [ROCm/rpp#473]
### Problem Description

Use amd provided clang++

### Operating System

ALL

### CPU

ALL

### GPU

AMD Instinct MI300

### ROCm Version

ROCm 6.0.0

### ROCm Component

rpp

**Comment by kiritigowda** [comment]
@LakshmiKumar23 PR #480 adds support to use AMD Clang++

**Comment by kiritigowda** [comment]
Fix merged
